### ISSUE TITLE
Package doesn't exist on npm?

### ISSUE THREAD

**Issue by laggingreflex** [simlrh/dead-css-loader#1]
https://www.npmjs.com/package/dead-css-loader

Just found this, looks really promising!

**Comment by simlrh** [comment]
Thanks. ATM it depends on changes to css-loader and style-loader that haven't been merged yet. I'll publish if/when that happens. 

To try it now you can depend on the git URL, see the example project.

**Comment by ankurp** [comment]
Great job for working on this since currently Tree shaking does not work for CSS. I noticed your PRs have been stale and not worked on. css-loader and style loader team have been willing to accept your changes but waiting for you to rebase your code with latest changes from master. Will your changes be published soon?

**Comment by simlrh** [comment]
I don't really work on web stuff any more, and the bits I do use CSS in JS, so personally I can't see a use case for this going forward.

If anyone else wants to take over feel free!
